name: Direkt Laminat CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:

  deploy-dev:
    name: Deploy to DEV
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Deploy Backend (DEV)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'orderflow-pro-dev-be'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV_BE }}
          package: backend

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend (DEV)
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_URL: ${{ secrets.DEV_API_URL }}

      - name: Deploy Frontend (DEV)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'orderflow-pro-dev-fe'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV_FE }}
          package: frontend/dist


  deploy-prod:
    name: Deploy to PROD
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Deploy Backend (PROD)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'orderflow-pro-prod-be'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD_BE }}
          package: backend

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend (PROD)
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_URL: ${{ secrets.PROD_API_URL }}

      - name: Deploy Frontend (PROD)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'orderflow-pro-prod-fe'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD_FE }}
          package: frontend/dist